-- MySQL Script generated by MySQL Workbench
-- Mon Apr  4 21:33:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crm-fotografia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema crm-fotografia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm-fotografia` DEFAULT CHARACTER SET utf8 ;
USE `crm-fotografia` ;

-- -----------------------------------------------------
-- Table `crm-fotografia`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm-fotografia`.`clientes` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nomecliente` VARCHAR(45) NOT NULL,
  `dtnasccliente` DATETIME NULL,
  `dtcadcliente` DATETIME NOT NULL,
  `email` VARCHAR(45) NULL,
  `whatsapp` VARCHAR(11) NULL,
  `enderecocliente` VARCHAR(250) NULL,
  `numeroendcliente` VARCHAR(8) NULL,
  `bairrocliente` VARCHAR(45) NULL,
  `cepcliente` CHAR(8) NULL,
  `cidadecliente` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm-fotografia`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm-fotografia`.`servicos` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `tiposervico` ENUM('newborn', 'ensaio grávida', 'acompanhamento', 'casamento') NOT NULL,
  `ambienteservico` ENUM('fora', 'em casa') NOT NULL,
  `dtcadservico` DATETIME NOT NULL,
  `dtevento` DATETIME NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `statusservico` ENUM('cancelado', 'agendado', 'aguardando entrada', 'aguardando autorizar') NOT NULL,
  `enderecoevento` VARCHAR(45) NULL,
  `numero` VARCHAR(8) NULL,
  `bairro` VARCHAR(45) NULL,
  `cep` CHAR(8) NULL,
  `cidade` VARCHAR(45) NULL,
  `nomebebe` VARCHAR(45) NULL,
  `dtnascbebe` DATETIME NULL,
  `nomecrianca` VARCHAR(45) NULL,
  `dtnasccrianca` DATETIME NULL,
  `idcliente` INT NULL,
  PRIMARY KEY (`idservico`),
  INDEX `idcliente_idx` (`idcliente` ASC) VISIBLE,
  CONSTRAINT `idcliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `crm-fotografia`.`clientes` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm-fotografia`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm-fotografia`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_usuario_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
