@baseUrl = http://localhost:3001

### Registrar Cliente
POST {{ baseUrl }}/api/clientes
Content-Type: application/json

{
	"nome": "Clebson 2",
    "cpf":"38079871851",
    "dataCadastro": 12312312,
    "email": "email@gmail.comm",
    "foto": "foto",
    "origem": "facebook",
    "whatsapp": "11934875087"
}